### ISSUE TITLE
Any one can update and delete any one post.And also all blog store in database beside user id -1 

### ISSUE THREAD

**Issue by siumhossain** [yezz123/DogeAPI#1]
**Here is the issue**

**See im logged in as different id,but i can upload other's post which belongs to others**

![1](https://user-images.githubusercontent.com/56468488/118401456-a4ffcd80-b687-11eb-911e-8d191aa2e487.png)

![3](https://user-images.githubusercontent.com/56468488/118401528-df696a80-b687-11eb-8b6f-e762310cd331.png)

![5](https://user-images.githubusercontent.com/56468488/118401532-e42e1e80-b687-11eb-966a-a00667987755.png)

![4](https://user-images.githubusercontent.com/56468488/118401540-eabc9600-b687-11eb-8184-fa7c71adc318.png)

And every blog stored beside user id 1

Here is your database screen shot
![2](https://user-images.githubusercontent.com/56468488/118401573-03c54700-b688-11eb-9971-23277e72b11c.png)

**Comment by yezz123** [comment]
Thank you @siumhossain for reporting this. 🙏🏻 
Am still working on the second Part of user_ID to be stored with a different number or a random one, for the first part when you run the DogeAPI you can control all the get & post and u have the access to write and maintain all of them.
This is not a bug it's a part of the administration to control all the GET & POST.

**Comment by siumhossain** [comment]
Ok waiting for 2nd part❤️
